### ISSUE TITLE
Move this repo to httpie organization

### ISSUE THREAD

**Issue by msabramo** [httpie/httpie-unixsocket#11]
Transfer https://github.com/msabramo/httpie-unixsocket to the [`httpie` org](https://github.com/httpie) (as [@jkbrzt had suggested](https://github.com/jkbrzt/httpie/issues/540#issuecomment-265887516)).

Cc: @jkbrzt

**Comment by msabramo** [comment]
Done.  We're now at https://github.com/httpie/httpie-unixsocket

**Comment by jkbrzt** [comment]
Awesome! 👏
